### ISSUE TITLE
Live TV streaming no longer works as of Kodi 21

### ISSUE THREAD

**Issue by alex-taylor** [kodi-pvr/pvr.argustv#193]
Trying to start a live TV stream under Kodi 21 fails after a few seconds.

In the Kodi UI, you see the busy spinner as it waits for the stream to start; after about 10 seconds this disappears and that's your lot.

Argus is starting the stream without any problems - the .tsbuffer and .ts files are created and written to as normal; the problem is that Kodi (via the plugin) is not reading from them.

I've done some debugging around this, using the Omega branch of the plugin, and the problem stems from recent(ish) changes made to Kodi's virtual filesystems.  Specifically, as of Kodi 21 the ADDON_READ_CHUNKED mode appears to be broken (and, as of the ongoing development of Kodi 22, it has been removed entirely).

What appears to be going on is that each time MultiFileReader::RefreshTSBufferFile() reads the value of 'currentPosition' from the .tsbuffer file, it just gets the same value back.  The exact value depends on how much of the .ts file had been written by Argus at the point when the first call to RefreshTSBufferFile() was made, but once that file is read it will, from the point of view of the plugin, never change again, and so the plugin concludes that it has reached the end of the stream.  The implication, of course, is that the file is cached.

Changing FileReader::OpenFile() to open the file as ADDON_READ_NO_CACHE instead doesn't fix the issue, which suggests further that Kodi has another bug and this flag no longer disables the cache.

Changing it to open as READ_NO_BUFFER resolves the issue, although I haven't done enough testing yet to confirm whether this is reliable long-term.

The current status appears to be this:

- The official release of Kodi 20 : all working normally
- The official release of Kodi 21.1 : Live TV streaming is broken as described above, but - and this is interesting - changing the read-flag does _not_ fix it
- The latest nightly build of Kodi 21 _does_ work, so long as you change the flag to READ_NO_BUFFER

I haven't tested the nightly build of Kodi 22 yet.

If the fix I'm proposing above - to use READ_NO_BUFFER when opening the files - is acceptable, I can raise a PR for the change.  Please let me know!  If not, I'll be more than happy to dig further into the problem (I do have a vested interest in getting this to work!) and I'd like to ask for some advice on how to proceed.

**Comment by phunkyfish** [comment]
Thanks for debugging.

Before we go with the read no buffer fix can you try with `READ_NO_CACHE | READ_TRUNCATED | READ_BITRATE` and report back?

The above may also work and is closer to the old behaviour.

**Comment by alex-taylor** [comment]
Just tried that - same result as before, the stream doesn't play.

If I'm correct about the file being cached despite the 'no cache' flag, that would make sense, of course!

**Comment by alex-taylor** [comment]
Just to add - I've done a longer (~35 minutes) test with the 'no buffer' fix and it appears to be stable.

**Comment by phunkyfish** [comment]
Ok. Then let’s go with the no buffer fix.

You’ll need to PR it for v22 and V21. And thanks in advance for contributing.

**Comment by alex-taylor** [comment]
I seem to be unable to push to the repo.  I've got my PAT set up and working, but anything I try just results in a 403 error.

**Comment by phunkyfish** [comment]
Did you fork the repo and push to your updated branch to your fork?

**Comment by alex-taylor** [comment]
Ah, that would be it!  Sorry, not worked on someone else's repo before.

Two PRs now raised.  Thanks!

**Comment by phunkyfish** [comment]
Thanks so much for the contribution. All merged and released now!
