### ISSUE TITLE
Support for Kodi 18

### ISSUE THREAD

**Issue by axlt2002** [kodi-pvr/pvr.argustv#73]
Hi,

I'm just wondering if there is (or will be) a work ongoing to make pvr.argustv compatible with Kodi 18. The actaul nightly version of Kodi does not include the pvr for ArgusTV (check [this thread](https://forum.kodi.tv/showthread.php?tid=320608) on the Kodi forum).

Thanks in advance for any feedback.

Alex

**Comment by ksooo** [comment]
If no dev picks up the task, nothing will happen. That life with FOSS.

**Comment by axlt2002** [comment]
Yup, I agree.

But looking at the commits stroy, it seems that there is still something moving. That is why I asked about Kodi 18 support.

**Comment by ksooo** [comment]
I try to do what I can, but some API changes require in depth knowledge of the addon implementation. When it comes to this point (and that happend with recent API changes) I'm out and a real addon maintainer comes into play. If nobody steps up o the original maintainer vanished, ... this addon is doomed.

**Comment by patrickplummers4** [comment]
I've done a couple of things in the past but various commits have gone unmerged for months.  If the original maintainers won't step forward, I'll fork and continue on from there.   I was looking at updating to the later api support for scheduled recordings control.

**Comment by ksooo** [comment]
@patrickplummers4 I would highly prefer you submitting PRs to this repo over forking. I'd say, let's give it a try.

**Comment by axlt2002** [comment]
Something is moving then...thanks in advance guys!

**Comment by margro** [comment]
@patrickplummers4 Feel free to update the addon. I'm the original author, but I have no working ArgusTV backend anymore. It fails to run properly on my current HTPC, therefore I cannot do much development on this addon anymore. Changing the addon is no problem, but I cannot test it myself.

**Comment by bernhardberger** [comment]
seems like ArgusTV + Kodi is doomed.. as there currently is no way (known to me) to get MTD working with Digital Devices DuoFlex S2 on a linux machine this is a real shame :/

**Comment by Jalle19** [comment]
What is MTD?

**Comment by bernhardberger** [comment]
Multi Transponder Decrypting. I really (like no-way-in-hell really) want to go back to MediaPortal as TV Server or fiddle around with softcam solutions anymore.

I'd support the development (I'm a coder and also have experience with C/C++, .NET and more) but I'm very short on time to read into the neeeded changes..

**Comment by Jalle19** [comment]
AFAIK tvheadend on Linux supports that.

**Comment by bernhardberger** [comment]
Only with a softcam solution. I don't want that. But here in Austria even
the public channels are encrypted. If you add paytv I'd need 5 cards and
CIs/CAMs or more without MTD..

Am 17.10.2017 8:01 nachm. schrieb "Sam Stenvall" <notifications@github.com>:

**Comment by Jalle19** [comment]
It supports hardware CAMs these days too. I'm not sure about MTD though but it's pretty feature-rich so I wouldn't be surprised if it does.

**Comment by bernhardberger** [comment]
The successtories are very thin and tbh I 4TR/ArgusTV has served me well now for more than a decade. This topic is drifting away sadly

**Comment by ksooo** [comment]
At least it has good Kodi support, which is a big difference to ArgusTV it seems.

**Comment by bernhardberger** [comment]
Agreed. Doesn't help me (at all) however if MTD is a massive PITA on anything else then Windows+Argus. I'd love to get rid of the M$ stuff on my HTPC as it's the only one in the household that doesn't run a unix based OS.

If you however have 3 different paytv (and freetv, yeah they're encrypted in Austria too....) providers on one smartcard you have no choice other than to rely on MTD.

And this is currently only possible with Digital Devices Octopus CIs and ArgusTV (Mediaportal TV Server is bug filled and unstable, NextPVR doesn't work with Digital Devices Duoflex cards and DVBLink doesn't have the ability to share a CAM/CI with more than one tuner simultabiously...

This whole PayTV/Encryption scene is ruining everything nowadays

**Comment by Jalle19** [comment]
Honestly though I would just use a softcam if I were you, would save you all the trouble.

**Comment by bernhardberger** [comment]
Not an option really as I'm forced to using an Unicam for my smartcards...

Am 24.10.2017 21:02 schrieb "Sam Stenvall" <notifications@github.com>:

**Comment by ksooo** [comment]
Well, don't get me wrong, but if you are a developer, it seems to me you'd better invest time in getting familiar with the code and start fixing shit instead of writing long walls of text in this issue. ;-)

**Comment by bernhardberger** [comment]
@ksooo agreed. It however isn't easy doing so on my phone during lunch break and especially wothout any sort of windows machine I could develop on ;-)

**Comment by ksooo** [comment]
Well, sometimes it helps to do nothing, to lean back and to wait until somebody else does the job. Like @fuzzard did in this case.
